config/routes.rb
GemsStatusWeb::Application.routes.draw do
  get 'home', to: 'home#index'
  get 'sa_similars', to:'home#sa_similars'
  get 'ping', to: 'home#ping'
  resources :reports
  resources :sessions
  resources :source_repos

  resources :security_alerts

  resources :users do
    get 'import_repos'
    get :generate_access_token
    get :switch_off_email
    get :switch_on_email
  end

  resources :ruby_applications do
    get 'result'
  end

  root 'sessions#new'

  get "/auth/:provider/callback" => "sessions#create"

  

end

app/models/source_repo.rb
class SourceRepo < ActiveRecord::Base
  validates :name, presence: true
  validates :url, presence: true
end

app/controllers/source_repos_controller.rb
class SourceReposController < ApplicationController
  before_action :set_source_repo, only: [:show, :edit, :update, :destroy]

  # GET /source_repos
  # GET /source_repos.json
  def index
    @source_repos = SourceRepo.all
  end

  # GET /source_repos/1
  # GET /source_repos/1.json
  def show
  end

  # GET /source_repos/new
  def new
    @source_repo = SourceRepo.new
  end

  # GET /source_repos/1/edit
  def edit
  end

  # POST /source_repos
  # POST /source_repos.json
  def create
    @source_repo = SourceRepo.new(source_repo_params)

    respond_to do |format|
      if @source_repo.save
        format.html { redirect_to @source_repo, notice: 'Source repo was successfully created.' }
        format.json { render action: 'show', status: :created, location: @source_repo }
      else
        format.html { render action: 'new' }
        format.json { render json: @source_repo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /source_repos/1
  # PATCH/PUT /source_repos/1.json
  def update
    respond_to do |format|
      if @source_repo.update(source_repo_params)
        format.html { redirect_to @source_repo, notice: 'Source repo was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @source_repo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /source_repos/1
  # DELETE /source_repos/1.json
  def destroy
    @source_repo.destroy
    respond_to do |format|
      format.html { redirect_to source_repos_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_source_repo
      @source_repo = SourceRepo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def source_repo_params
      params.require(:source_repo).permit(:name, :url)
    end
end

app/helpers/source_repos_helper.rb
module SourceReposHelper
end

app/views/source_repos/_form.html.erb
<%= form_for(@source_repo) do |f| %>
  <% if @source_repo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@source_repo.errors.count, "error") %> prohibited this source_repo from being saved:</h2>

      <ul>
      <% @source_repo.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :url %><br>
    <%= f.text_field :url %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/source_repos/edit.html.erb
<h1>Editing source_repo</h1>

<%= render 'form' %>

<%= link_to 'Show', @source_repo %> |
<%= link_to 'Back', source_repos_path %>

app/views/source_repos/index.html.erb
<h1>Listing source_repos</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Url</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @source_repos.each do |source_repo| %>
      <tr>
        <td><%= source_repo.name %></td>
        <td><%= source_repo.url %></td>
        <td><%= link_to 'Show', source_repo %></td>
        <td><%= link_to 'Edit', edit_source_repo_path(source_repo) %></td>
        <td><%= link_to 'Destroy', source_repo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<div id="actions">
  <%= link_to 'New Source repo', new_source_repo_path %>
</div>

app/views/source_repos/new.html.erb
<h1>New source_repo</h1>

<%= render 'form' %>

<%= link_to 'Back', source_repos_path %>

app/views/source_repos/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @source_repo.name %>
</p>

<p>
  <strong>Url:</strong>
  <%= @source_repo.url %>
</p>

<%= link_to 'Edit', edit_source_repo_path(@source_repo) %> |
<%= link_to 'Back', source_repos_path %>