config/routes.rb
GemsStatusWeb::Application.routes.draw do
  get 'home', to: 'home#index'
  get 'sa_similars', to:'home#sa_similars'
  get 'ping', to: 'home#ping'
  resources :reports
  resources :sessions
  resources :source_repos

  resources :security_alerts

  resources :users do
    get 'import_repos'
    get :generate_access_token
    get :switch_off_email
    get :switch_on_email
  end

  resources :ruby_applications do
    get 'result'
  end

  root 'sessions#new'

  get "/auth/:provider/callback" => "sessions#create"

  

end

app/models/user.rb
require "open-uri"

class User < ActiveRecord::Base
  before_create :generate_access_token!
  has_many :ruby_applications
  has_many :repos
  validates :name, presence: true
  validates :email, presence: true, uniqueness: true
  validates :times_logged_in, numericality: { only_integer: true }
  validates :receive_emails, presence: true
  
  has_secure_password(validations: false)

  def receive_emails?
    receive_emails != 0
  end

  def repo_names
    repos.collect(&:name)
  end

  def reviewed_sa
    counter = 0
    ruby_applications.each do |ra|
      counter = counter + ra.security_alerts.where("status != 0").count
    end
    counter
  end

  def import_repos
    return unless auth_token
    Rails.logger.debug "initializing octokit"
    begin
      client = Octokit::Client.new :access_token => auth_token
      user = client.user
      if user.nil?
        Rails.logger.error "there was some kind of problem logging to github"
        return
      end
      Rails.logger.debug "login"
      user.login
      Rails.logger.debug "get repos"
      repos = user.rels[:repos]
      if repos.nil?
        Rails.logger.error "there was some kind of problem getting repos from github"
        return
      end
      repos = repos.get
      if repos.nil?
        Rails.logger.error "there was some kind of problem getting repos from github"
        return
      end
      repos = repos.data
      if repos.nil?
        Rails.logger.error "there was some kind of problem getting repos from github"
        return
      end
    rescue Exception => e
      Rails.logger.error "there was some kind of problem interacting with github #{e.message}"
      return
    end
    return if !repos
    repos.each do |repo|
      if !Repo.find_by_name(repo.name)
        begin
          filename = "https://raw.github.com/#{name}/#{repo.name}/master/Gemfile.lock"
          Rails.logger.debug "trying to download #{filename}"
          open(filename)
        rescue
          Rails.logger.debug "#{filename} does not exist. Ignoring repo ..."
          next
        end
        Rails.logger.debug "saving repo to database"
        r = Repo.new
        r.name = repo.name
        r.user = self
        if !r.save
          Rails.logger.debug "Some error occured saving repo #{r.name}"
        end
      end
    end
  end

  def generate_access_token!
    begin
      self.api_access_token = SecureRandom.hex
    end while self.class.exists?(api_access_token: api_access_token)
  end

  private

  def self.create_with_omniauth(auth)
    create! do |user|
      user.provider = auth["provider"]
      user.uid = auth["uid"]
      user.name = auth["info"]["nickname"]
      user.email = auth["info"]["email"]
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @path = User.find(params[:id]).name
  end

  # GET /users/1/import_repos
  def import_repos
    @user = User.find(params[:user_id])
    @user.delay.import_repos
    redirect_to @user, notice: "Import repos action triggered"
  end

  # GET /users/1/generate_access_token
  def generate_access_token
    @user = User.find(params[:user_id])
    @user.generate_access_token!
    @user.save
    redirect_to @user, notice: "Access token generated"
  end

  # GET /users/1/switch_on_email
  def switch_on_email
    @user = User.find(params[:user_id])
    @user.receive_emails = 1
    @user.save
    redirect_to @user
  end

  # GET /users/1/switch_off_email
  def switch_off_email
    @user = User.find(params[:user_id])
    @user.receive_emails = 0
    @user.save
    redirect_to @user
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render action: 'show', status: :created, location: @user }
      else
    require "debugger";debugger
        format.html { render action: 'new' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /user/1
  # PUT /user/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation, :admin, :role, :beta_user)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>
      <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <% if !CONFIG['GITHUB_INTEGRATION'] %>
    <div class="field">
      <%= f.label :name %><br>
      <%= f.text_field :name %><br>
      <%= f.label :email %><br>
      <%= f.text_field :email %><br>
    </div>
    <div class="field">
      <%= f.label :password %><br />
      <%= f.password_field :password %>
    </div>
    <div class="field">
      <%= f.label :password_confirmation %><br />
      <%= f.password_field :password_confirmation %>
    </div>
  <% end %>
  <div class="field">

    <%= f.check_box(:admin) %>
    <%= f.label(:admin, "Is admin?") %>
</div>
  <div class="field">
    <%= f.check_box(:role) %>
    <%= f.label(:role, "security team") %>
</div>
  <div class="field">
    <%= f.check_box(:beta_user) %>
    <%= f.label(:beta_user, "beta user") %>
</div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>
<%= link_to "Regenerate access token", user_path(@user) + "/generate_access_token" %>
<br/>
<%= link_to "Back", users_path %>

app/views/users/index.html.erb
<h1>Users(<%= @users.count %>)</h1>

<table>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= link_to user.name, user %></td>
        <td><%= user.times_logged_in %> times logged in</td>
        <td>
          <% if user.beta_user%>
            Beta User
          <% end %> 
        </td>
        <td><%= user.reviewed_sa %> sa reviewed</td>
        <td><%= link_to "Edit", edit_user_path(user) %></td>
        <td><%= link_to "Destroy", user, method: :delete, data: { confirm: "Are you sure?" } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<div id="actions">
  <%= link_to 'New User', new_user_path %>
  |
  <%= link_to 'Source repos', source_repos_path %>
  |
  <%= link_to 'Reports', reports_path %>
</div>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @user.name %>
  <br/>
  <strong>Email:</strong>
  <%= @user.email %>
  <br />
  <strong>Ruby applications</strong>
  <ul>
  <% @user.ruby_applications.each do |ra| %>
    <li>
      <%= link_to ra.name, ruby_application_path(ra) %>
    </li>
  <% end %>
  </ul>
  <br>
  <% if CONFIG['GITHUB_INTEGRATION'] %>
    <strong>Repos in github</strong>
    <ul>
    <% @user.repos.each do |r| %>
        <li>
         <%= r.name %>
        </li>
    <% end %>
    </ul>
    <br>
    <%= link_to "Import repos", user_path(@user) + "/import_repos" %>
    <br>
  <% end %>
  <strong>API access token: </strong>
  <%= @user.api_access_token %>
  <br/>
  <%= link_to "Regenerate access token", user_path(@user) + "/generate_access_token" %>
  <br>
  <% if @user.receive_emails? %>
    <%= link_to "Stop receiving emails", user_path(@user) + "/switch_off_email" %>
  <% else %>
    <%= link_to "Start receiving emails", user_path(@user) + "/switch_on_email" %>
  <% end %>
</p>