config/routes.rb
GemsStatusWeb::Application.routes.draw do
  get 'home', to: 'home#index'
  get 'sa_similars', to:'home#sa_similars'
  get 'ping', to: 'home#ping'
  resources :reports
  resources :sessions
  resources :source_repos

  resources :security_alerts

  resources :users do
    get 'import_repos'
    get :generate_access_token
    get :switch_off_email
    get :switch_on_email
  end

  resources :ruby_applications do
    get 'result'
  end

  root 'sessions#new'

  get "/auth/:provider/callback" => "sessions#create"

  

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @security_alerts = []
    current_user.ruby_applications.each do |ra|
      sa = ra.filtered_security_alerts
      @security_alerts << sa
    end
    @security_alerts.flatten!
  end
  def sa_similars
    if !params["desc"]
      @similars = "specify desc"
      return
    end
    sa = SecurityAlert.new(
      :desc => params["desc"],
      :status => 0
    )
    @similars = sa.similars
    respond_to do |format|
      format.html { render 'sa_similars' }
      format.json { render json: @similars }
    end
  end

  def ping
  end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<% if current_user && !beta_user? %>
  Sorry. This is limited to beta_users.
  <% if CONFIG['BETA_USER_LINK'] %>
    If you'd like to be a beta user, <a href="<%= CONFIG['BETA_USER_LINK'] %>">contact us</a>.
  <% end %>

<% elsif current_user %>
  <p>Hi <%= current_user.name %>, welcome to <span class="alert"><%= request.host %></a></p>
  <% if !@security_alerts %>
    There are no security alerts.
  <% else %>
    <p>
    You have <%= @security_alerts.length %> possible security alerts for your ruby applications to review:
    </p>
    <table width="100%">
      <tr>
        <th>Ruby application</th>
        <th>Gem</th>
        <th>Version</th>
        <th>Security alert</th>
        <th>Status</th>
        <th>Fixed in</th>
      </tr>
      <% @security_alerts.each do |sa| %>
        <tr>
          <td>
            <%= link_to sa.ruby_application.name, ruby_application_path(sa.ruby_application) %>
          </td>
          <td>
            <%= sa.ruby_gem.name %>
          </td>
          <td>
            <%= sa.ruby_gem.version %>
          </td>
          <td>
            <%= link_to "#{sa.short_desc}", security_alert_path(sa) %>
          </td>
          <td>
            <%= sa.status_text %>
          </td>
          <td>
            <% if !sa.version_fix.nil? && !sa.version_fix.blank? %>
              <%= sa.version_fix %> 
            <% end %>
          </td>
        </tr>
      <% end %>
    </table>
  <% end %>
  <div id="actions">
  <%= link_to 'New ruby application', new_ruby_application_path %>
  </div>
<% end %>

app/views/home/ping.html.erb
ok

app/views/home/sa_similars.html.erb
<%= @similars %>