config/routes.rb
GemsStatusWeb::Application.routes.draw do
  get 'home', to: 'home#index'
  get 'sa_similars', to:'home#sa_similars'
  get 'ping', to: 'home#ping'
  resources :reports
  resources :sessions
  resources :source_repos

  resources :security_alerts

  resources :users do
    get 'import_repos'
    get :generate_access_token
    get :switch_off_email
    get :switch_on_email
  end

  resources :ruby_applications do
    get 'result'
  end

  root 'sessions#new'

  get "/auth/:provider/callback" => "sessions#create"

  

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= request.host %></title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
<% if CONFIG['GOOGLE_ANALYTICS'] %>
	<script>
	  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
	  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
	  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
	  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

	  ga('create', '<%= CONFIG['GOOGLE_ANALYTICS'] %>', 'redruby.io');
	  ga('send', 'pageview');

	</script>
<% end %>
</head>
<body>
<p id="notice"><%= notice %></p>
<p class="error"><%= flash[:error] %></p>
<div id="top-left">
  <% if current_user %>
    <%= link_to current_user.name, user_path(current_user) %>@<span class="alert"><%= link_to request.host, home_path %></span>/<%= @path %>:>
  <% end %>
</div>
<div id="top-right">
  <% if CONFIG['FEEDBACK_LINK'] %>
    <a target="_new" href="<%= CONFIG['FEEDBACK_LINK'] %>">Feedback</a>
    <% end %>
  <a target="_new" href="https://github.com/jordimassaguerpla/gems-status-web/blob/master/README.md">Help</a>
  <% if current_user %>
    <% if is_admin? %>
      <%= link_to "admin", users_path %>
    <% end %>
    <%= link_to "logout", session_path("current"), method: "delete" %>
  <% end %>
</div>

<%= yield %>
<!-- 
<br>
<p>
--------------------<br/>
Source code: <a href="http://www.github.com/jordimassaguerpla/gems-status-web">http://www.github.com/jordimassaguerpla/gems-status-web</a>
</p>
<p>
Analysis done by <a href="http://www.github.com/jordimassaguerpla/gems-status/">gems status <%= GemsStatus::VERSION %></a>
<br/>
<% if LastRun.last %>
  Last run <%= LastRun.last.created_at %>
  <br/>
  Run <%= LastRun.count %> times since <%= LastRun.first.created_at %>
<% end %>
</p>
 -->
</body>
</html>